name-template: 'v$RESOLVED_VERSION'
tag-template: 'v$RESOLVED_VERSION'
categories:
  - title: Features
    labels: ['feature', 'enhancement']
  - title: Bug Fixes
    labels: ['fix', 'bug']
  - title: Maintenance
    label: ['chore', 'dependencies']
  - title: Misc
    label: '*'
change-template: '- $TITLE @$AUTHOR (#$NUMBER)'
change-title-escapes: '\<*_&'
version-resolver:
  major:
    labels: ['major']
  minor:
    labels: ['minor']
  patch:
    labels: ['patch']
  default: patch
autolabeler:
  - label: chore
    files: ['.github/**']
    branch: ['/^refactor\/.+/']
    title: ['/^(?:build|chore|ci|refactor|style)(?:\([^)]+\))?:/']
  - label: fix
    branch: ['/^fix\/.+/']
    title: ['/^(?:fix|fixes|revert)(?:\([^)]+\))?:/']
  - label: enhancement
    branch: ['/^feat\/.+/']
    title: ['/^(?:feat|perf)(?:\([^)]+\))?:/']
  - label: documentation
    files: ['*.md']
    title: ['/^docs?(?:\([^)]+\))?:/']
  - label: test
    files: ['test/**']
    title: ['/^test(?:\([^)]+\))?:/']
template: |
  ## Changes

  $CHANGES

  $CONTRIBUTORS
