name: On Push Tag

on:
  # workflow_dispatch:
  #   inputs:
  #     tag_name:
  #       description: 'Tag to deploy'
  #       required: true
  #       type: string
  workflow_call:
    inputs:
      tag_name:
        description: 'Tag to deploy'
        required: true
        type: string

jobs:
  on-push-tags:
    name: Test the props
    runs-on: ubuntu-latest
    permissions:
      contents: write
      id-token: write
      packages: write
    steps:
      - uses: actions/checkout@v5
        with:
          ref: ${{ inputs.tag_name }}

      - name: Install pnpm and dependencies
        uses: pnpm/action-setup@v4
      - run: pnpm install --frozen-lockfile --ignore-scripts
      - run: pnpm install --global npm@11.5.1

      - run: |
          echo github.ref : "${{ github.ref }}"
          echo github.ref_type: ${{ github.ref_type }}
          echo Actor: ${{github.actor}} id: ${{github.actor_id}}, trigger: ${{github.triggering_actor}}
          echo Repository: ${{ github.repository }} - ${{ github.workspace }}
          echo Inputs: ${{ inputs.tag_name }}
      - name: Publish to GitHub
        run: pnpm publish --access public --no-git-checks
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
