name: On Push Tag

on:
  workflow_dispatch:
    inputs:
      tag:
        description: 'Tag de la version a publicar'
        required: true
        type: string
  workflow_call:

jobs:
  on-push-tags:
    name: Test the props
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo "${GITHUB_REF#refs/tags/v} --- ${GITHUB_REF}"
          echo github.ref : "${{ github.ref }}"
          echo Running in ${{ runner.os }}
          echo Actor: ${{github.actor}} id: ${{github.actor_id}}, trigger: ${{github.triggering_actor}}
          echo ${{ toJson(github.event)}}
