# Publish a new release if there's a version change in package.json

name: Release

on:
  push:
    branches: [main]
    paths: ['package.json']

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  publish_release:
    permissions:
      contents: write
      pull-requests: read
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v5
        with:
          fetch-depth: 2
          ref: main

      - name: Check version change
        uses: salsify/action-detect-and-tag-new-version@v2
        with:
          create-tag: false
        id: check

      # Drafts your next Release notes as Pull Requests are merged into "main"
      - name: Update or publish release draft
        if: steps.check.outputs.current-version != steps.check.outputs.previous-version
        uses: release-drafter/release-drafter@v6
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          publish: true
          version: ${{ steps.check.outputs.current-version }}
        id: draft

      # This is needed because https://github.com/actions/create-release/issues/71
      - name: Let us know about new release
        if: steps.check.outputs.current-version != steps.check.outputs.previous-version
        uses: peter-evans/repository-dispatch@v4
        with:
          event-type: 'release_published_evt'
          client-payload: |-
            {
              "id": "${{ steps.draft.outputs.id }}",
              "tag_name": "${{ steps.draft.outputs.tag_name }}"
            }

      - name: Using another action for deployment
        if: steps.check.outputs.current-version != steps.check.outputs.previous-version
        run: ./on-push-tag.yml
