name: On Release Published

on:
  repository_dispatch:
    types: [release_published_evt]
  workflow_call:
    inputs:
      version:
        description: 'Version to publish'
        required: true
        type: string

permissions:
  contents: read

jobs:
  on-push-tags:
    name: Test the props
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo github.ref : "${{ github.ref }}"
          echo Running in ${{ runner.os }}
          echo Actor: ${{github.actor}} id: ${{github.actor_id}}, trigger: ${{github.triggering_actor}}
          echo ${{ toJson(github.event) }}
          git status
