name: On Release Published

on:
  repository_dispatch:
    types: [release_published_evt]

permissions:
  contents: read

jobs:
  on-push-tags:
    name: Test the props
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo github.ref : "${{ github.ref }}"
          echo Running in ${{ runner.os }}
          echo Actor: ${{github.actor}} id: ${{github.actor_id}}, trigger: ${{github.triggering_actor}}
          echo Pay: '${{ github.event.client_payload }}'
